### ISSUE TITLE
Demo not working because of np.float_

### ISSUE THREAD

**Issue by LGiesken** [OFFIS-mosaik/mosaik#18]
Hello everyone,

I tried to install the demo of mosaik according to the instructions on readthedocs. But I ran into a problem. When executing demo.py I get the message that networkx uses the type np.fload_. However, this no longer exists since version 2.0 of numpy. Upgrading to the latest version of networkx unfortunately did not work either. Is this problem already known or is there already a fix for it?

Many thanks in advance.

**Comment by eike** [comment]
Hi!

Thanks for bringing this to our attention. I tried it on my machine and ran into similar issues.

- The issue with networkx can indeed be solved by updating the version of it, and network 3.3 should also work with mosak.
- Unfortunately, the demo also uses PYPOWER. This is a very old package and it has not been updated to support numpy 2.0. It is not developed by us, so I have no insight into whether an update is coming.

For now, if you want to see the demo, your best option is to install a pre-2.0 version of numpy. If you are using virtual environments, you can do this without interrupting your other work by doing `pip install "numpy<2"` within the virtual environment you use for mosaik.

I will also add that our current projects tend to use mosaik-pandapower instead of mosaik-pypower, and this should work with numpy 2. So going forward with mosaik, you should not run into this issue anymore. (We should really update the demo to use pandapower as well, though.)

**Comment by LGiesken** [comment]
That worked, thank you.
